### ISSUE TITLE
I can't use Rails-Constant in my controllers

### ISSUE THREAD

**Issue by arfl** [saturnflyer/surrounded-rails#2]
In my application controller, I have a method calling `Rails.cache`. But I get an error:
```bash
NoMethodError - undefined method 'cache' for Surrounded::Rails:Module
```
I can of cause use `::Rails.cache`, but I would better avoid it. In a Rails environment, `Rails` constant should really point to the constant of the framework.

**Comment by benwoodward** [comment]
+1

This also breaks any gems that use ```Rails.any_method```

**Comment by saturnflyer** [comment]
Wow. Sorry @arfl, somehow I hadn't seen this issue until now.

**Comment by arfl** [comment]
Thank you!

**Comment by arfl** [comment]
By the way, your book and your gems are awesome! We use them everywhere now... Thanks!
